apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::195992782325:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1RJBB498KCB0Q
      username: system:node:{{EC2PrivateDNSName}}
    - rolearn: arn:aws:iam::195992782325:role/UdacityFlaskDeployCBKubectlRole
      username: build
      groups:
      - system:masters
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-02-12T00:20:07Z"
  managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:data:
          .: {}
          f:mapRoles: {}
          f:mapUsers: {}
      manager: eksctl.exe
      operation: Update
      time: "2021-02-12T00:20:07Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1543"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 568c3b09-39df-48dd-81b0-85d21d9ee92c
