apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::195992782325:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-NYOHLWB0V9N1
      username: system:node:{{EC2PrivateDNSName}}
    - rolearn: arn:aws:iam::195992782325:role/UdacityFlaskDeployCBKubectlRole
      username: build
      groups:
      - system:masters
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-02-11T06:27:27Z"
  managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:data:
          .: {}
          f:mapRoles: {}
          f:mapUsers: {}
      manager: eksctl.exe
      operation: Update
      time: "2021-02-11T06:27:27Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1527"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 3e300d62-8770-4efc-a1ae-cf79e03eb8ff
