apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::195992782325:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1USEGIG1Y02XO
      username: system:node:{{EC2PrivateDNSName}}
    - rolearn: arn:aws:iam::195992782325:role/UdacityFlaskDeployCBKubectlRole
      username: build
      groups:
      - system:masters
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-02-12T01:55:18Z"
  managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:data:
          .: {}
          f:mapRoles: {}
          f:mapUsers: {}
      manager: eksctl.exe
      operation: Update
      time: "2021-02-12T01:55:18Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1495"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 7248d73b-741a-44a3-a0cc-b609308e4975
