apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::195992782325:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1XC9IOOC6YPP2
      username: system:node:{{EC2PrivateDNSName}}
    - rolearn: arn:aws:iam::195992782325:role/UdacityFlaskDeployCBKubectlRole
      username: build
      groups:
      - system:masters
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-06-15T03:00:53Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1565"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 6384441d-b722-4990-930b-7ed436d17dc4
