apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::195992782325:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-12R9M83PLD55Y
      username: system:node:{{EC2PrivateDNSName}}
      - rolearn: arn:aws:iam::195992782325:role/UdacityFlaskDeployCBKubectlRole
      username: build
      groups:
      - system:masters
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-02-11T05:08:01Z"
  managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:data:
          .: {}
          f:mapRoles: {}
          f:mapUsers: {}
      manager: eksctl.exe
      operation: Update
      time: "2021-02-11T05:08:01Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1672"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: c7d67535-5976-445c-9f05-f94ced00631c
