apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::195992782325:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-12G0U5N13NWE6
      username: system:node:{{EC2PrivateDNSName}}
    - rolearn: arn:aws:iam::195992782325:role/UdacityFlaskDeployCBKubectlRole
      username: build
      groups:
      - system:masters
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-02-10T05:56:01Z"
  managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:data:
          .: {}
          f:mapRoles: {}
          f:mapUsers: {}
      manager: eksctl.exe
      operation: Update
      time: "2021-02-10T05:56:01Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1351"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 2296f904-34f7-4fa2-88e0-8984a8b35f33
